baseURL = "https://postgresgallery.netlify.com/"
languageCode = "en-us"
title = "PostgreSQL Gallery"
theme = "ananke"
[params]
    custom_css = ["css/code-overflow.css"]
    # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
 background_color_class = "bg-white"
 featured_image = "images/hero.png"
